language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.4.6
  - DJANGO_VERSION=1.5.2
install:
  - pip install Django==$DJANGO_VERSION
  - python setup.py install
script:
  - make test
notifications:
  email:
    - dev@mediapop.co

